name: cice-core

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build -p cice-core --verbose
      - name: Clippy
        run: cargo clippy -p cice-core --verbose
      - name: Run tests
        run: cargo test -p cice-core  --verbose
